### ISSUE TITLE
nativelibs4java-parent 1.9-SNAPSHOT not deployed

### ISSUE THREAD

**Issue by ctrimble** [nativelibs4java/JavaCL#2]
Looks like a parent pom was missed when breaking up the project.  I am getting this error when including javacl-core 1.0-SNAPSHOT.

```
Failed to collect dependencies at com.nativelibs4java:javacl-core:jar:1.0-SNAPSHOT:
Failed to read artifact descriptor for com.nativelibs4java:javacl-core:jar:1.0-SNAPSHOT:
Could not find artifact com.nativelibs4java:nativelibs4java-parent:pom:1.9-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/)
```

**Comment by ctrimble** [comment]
Looks like this might be related to the release of the nativelibs4java-parent pom version 1.9.  Sonatype prunes SNAPSHOTs with releases, so the old dependency is now missing.  Those on javacl-core 1.0-SNAPSHOT are going to have build issues until a new SNAPSHOT is pushed with the released parent.

**Comment by ochafik** [comment]
I inadvertently deployed a 1.0.0-SNAPSHOT instead of a 1.0-SNAPSHOT, my bad!

Reployed 1.0-SNAPSHOT :-)

**Comment by ctrimble** [comment]
@ochafik If the current version does not depend on any SNAPSHOTs and a working version of 1.0-SNAPSHOT is deployed, it might be a good time to move from `1.0-SNAPSHOT` to `1.0.0-SNAPSHOT`, since releases of dependencies will no longer break the library.

Again, thanks for moving this library out into a separate repo.
